CORE=$HOME/core
APPS=$HOME/apps

export PATH=$PATH:/usr/local/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$CORE/scripts
export PATH=$PATH:$APPS/flatc

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export ZSH=$HOME/.oh-my-zsh
export EDITOR=nvim

alias back="cd -"
alias xplore="xdg-open ."
alias vim="nvim"

function proj() {
    cd "$HOME/core/projects/$1"
}

function script() {
    if [ -z "$1"]; then
        echo "Pleas provide config name e.g zsh/zshrc"
	return
    fi
    $EDITOR "$HOME/core/configs/$1"
}

# force set cyrilic font in tty
tty | grep "/dev/tty[0-9]" && setfont cyr-sun16

ZSH_THEME="arrow"
plugins=(git)

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"


source $ZSH/oh-my-zsh.sh
